disabled_rules: # rule identifiers turned on by default to exclude from running
  - class_delegate_protocol
  - weak_delegate
    # Need to resolve
  - force_cast
  - force_try
  - line_length
  - todo
  - identifier_name
  - function_parameter_count
  - function_body_length
  - large_tuple
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - implicit_getter
  - nesting
  - legacy_constructor
  - file_length
