//
//  RangeSlider.swift
//  PennMobile
//
//  Created by Jonathan Melitski on 4/28/26.
//  Copyright © 2026 PennLabs. All rights reserved.
//

//  Generated by Claude because I didn't feel like building this from scratch

import SwiftUI

// MARK: - RangeSlider

struct RangeSlider<V: BinaryFloatingPoint, Content: View>: View
    where V.Stride: BinaryFloatingPoint
{
    // MARK: Public interface

    @Binding var lowerValue: V
    @Binding var upperValue: V

    /// The full range of valid values.
    let bounds: ClosedRange<V>

    /// Discrete step size. Pass `nil` for continuous (default).
    var step: V? = nil

    /// Minimum value-space gap between the two knobs.
    /// Defaults to 1 % of the total range when `nil`.
    var minimumSpan: V? = nil

    // MARK: Layout

    var knobDiameter: CGFloat = 28
    var trackHeight:  CGFloat = 4

    // MARK: Label

    let label: (V) -> Content
    var labelSpacing: CGFloat = 8
    @State private var measuredLabelHeight: CGFloat = 0

    // MARK: Drag state

    @State private var isDraggingLower = false
    @State private var isDraggingUpper = false

    // MARK: Body

    var body: some View {
        GeometryReader { geo in
            let trackWidth = geo.size.width - knobDiameter
            let lowerX     = xPosition(for: lowerValue, trackWidth: trackWidth)
            let upperX     = xPosition(for: upperValue, trackWidth: trackWidth)

            ZStack(alignment: .leading) {

                // ── Background track ─────────────────────────────────────────
                Capsule()
                    .fill(.secondary.opacity(0.2))
                    .frame(height: trackHeight)
                    .padding(.horizontal, knobDiameter / 2)
                    .offset(y: (measuredLabelHeight + labelSpacing) / 2)

                // ── Active fill ──────────────────────────────────────────────
                Capsule()
                    .fill(.tint)
                    .frame(
                        width:  max(0, (upperX + knobDiameter / 2) - (lowerX + knobDiameter / 2)),
                        height: trackHeight
                    )
                    .offset(x: lowerX + knobDiameter / 2, y: (measuredLabelHeight + labelSpacing) / 2)

                // ── Lower label + knob ───────────────────────────────────────
                VStack(spacing: labelSpacing) {
                    label(lowerValue)
                        .onGeometryChange(for: CGFloat.self, of: { $0.size.height }) {
                            measuredLabelHeight = $0
                        }
                    KnobView(isDragging: isDraggingLower, diameter: knobDiameter)
                        .gesture(
                            DragGesture(minimumDistance: 0, coordinateSpace: .named("RangeSlider"))
                                .onChanged { drag in
                                    isDraggingLower = true
                                    let raw     = value(at: drag.location.x - knobDiameter / 2, trackWidth: trackWidth)
                                    let ceiling = upperValue - effectiveMinSpan
                                    lowerValue  = clamp(raw, lo: bounds.lowerBound, hi: ceiling)
                                }
                                .onEnded { _ in isDraggingLower = false }
                        )
                }
                .position(
                    x: lowerX + knobDiameter / 2,
                    y: (measuredLabelHeight + labelSpacing) / 2 + knobDiameter / 2
                )
                .zIndex(isDraggingLower ? 2 : 1)

                // ── Upper label + knob ───────────────────────────────────────
                VStack(spacing: labelSpacing) {
                    label(upperValue)
                    KnobView(isDragging: isDraggingUpper, diameter: knobDiameter)
                        .gesture(
                            DragGesture(minimumDistance: 0, coordinateSpace: .named("RangeSlider"))
                                .onChanged { drag in
                                    isDraggingUpper = true
                                    let raw    = value(at: drag.location.x - knobDiameter / 2, trackWidth: trackWidth)
                                    let floor  = lowerValue + effectiveMinSpan
                                    upperValue = clamp(raw, lo: floor, hi: bounds.upperBound)
                                }
                                .onEnded { _ in isDraggingUpper = false }
                        )
                }
                .position(
                    x: upperX + knobDiameter / 2,
                    y: (measuredLabelHeight + labelSpacing) / 2 + knobDiameter / 2
                )
                .zIndex(isDraggingUpper ? 2 : 1)
            }
            .coordinateSpace(.named("RangeSlider"))
        }
        .frame(height: knobDiameter + measuredLabelHeight + labelSpacing)
        .sensoryFeedback(.impact(flexibility: .solid, intensity: 0.8), trigger: lowerValue) { old, new in
            guard let step else { return false }
            return abs(new - old) >= step * 0.5
        }
        .sensoryFeedback(.impact(flexibility: .solid, intensity: 0.8), trigger: upperValue) { old, new in
            guard let step else { return false }
            return abs(new - old) >= step * 0.5
        }
    }

    // MARK: Value ↔ pixel helpers

    private func xPosition(for val: V, trackWidth: CGFloat) -> CGFloat {
        let span = bounds.upperBound - bounds.lowerBound
        guard span > 0 else { return 0 }
        return CGFloat((val - bounds.lowerBound) / span) * trackWidth
    }

    private func value(at x: CGFloat, trackWidth: CGFloat) -> V {
        let span  = bounds.upperBound - bounds.lowerBound
        let ratio = V(max(0, min(CGFloat(1), x / max(trackWidth, 1))))
        let raw   = ratio * span + bounds.lowerBound
        guard let step, step > 0 else { return raw }
        return (raw / step).rounded() * step
    }

    private var effectiveMinSpan: V {
        minimumSpan ?? ((bounds.upperBound - bounds.lowerBound) / 100)
    }

    private func clamp(_ val: V, lo: V, hi: V) -> V {
        max(lo, min(hi, val))
    }
}

// MARK: - Inits

extension RangeSlider {
    /// Primary init — caller supplies a label view for each knob.
    init(
        lowerValue:  Binding<V>,
        upperValue:  Binding<V>,
        bounds:      ClosedRange<V>,
        step:        V? = nil,
        minimumSpan: V? = nil,
        labelSpacing: CGFloat = 8,
        @ViewBuilder label: @escaping (V) -> Content
    ) {
        self._lowerValue  = lowerValue
        self._upperValue  = upperValue
        self.bounds       = bounds
        self.step         = step
        self.minimumSpan  = minimumSpan
        self.labelSpacing = labelSpacing
        self.label        = label
    }
}

extension RangeSlider where Content == EmptyView {
    /// No-label init — Content pins to EmptyView, measuredLabelHeight stays 0.
    init(
        lowerValue:  Binding<V>,
        upperValue:  Binding<V>,
        bounds:      ClosedRange<V>,
        step:        V? = nil,
        minimumSpan: V? = nil
    ) {
        self.init(lowerValue: lowerValue, upperValue: upperValue,
                  bounds: bounds, step: step, minimumSpan: minimumSpan,
                  label: { _ in EmptyView() })
    }
}

extension RangeSlider where V == Double, Content == EmptyView {
    /// Int-step sugar, no label.
    init(
        lowerValue:  Binding<Double>,
        upperValue:  Binding<Double>,
        bounds:      ClosedRange<Double>,
        step:        Int,
        minimumSpan: Double? = nil
    ) {
        self.init(lowerValue: lowerValue, upperValue: upperValue,
                  bounds: bounds, step: Double(step), minimumSpan: minimumSpan)
    }
}

// MARK: - KnobView

private struct KnobView: View {
    let isDragging: Bool
    let diameter: CGFloat

    var body: some View {
        ZStack {
            if #available(iOS 26, *) {
                Circle()
                    .fill(.white)
                    .glassEffect(isDragging ? .clear : .identity, in: Circle())
            } else {
                Circle()
                    .fill(.white)
                Circle()
                    .strokeBorder(.tint.opacity(0.3), lineWidth: 1)
            }
        }
        .frame(width: diameter, height: diameter)
        .contentShape(Circle())
        .shadow(
            color:  .black.opacity(0.18),
            radius: isDragging ? 14 : 6,
            y:      isDragging ?  6  : 2
        )
        .scaleEffect(isDragging ? 1.3 : 1.0)
        .animation(.spring(response: 0.25, dampingFraction: 0.6), value: isDragging)
    }
}

// MARK: - Preview

#Preview("Range Slider") {
    @Previewable @State var lo: Double = 20
    @Previewable @State var hi: Double = 75
    @Previewable @State var loF: Float = 0.3
    @Previewable @State var hiF: Float = 0.9

    ScrollView {
        VStack(alignment: .leading, spacing: 36) {

            // With labels
            RangeSlider(lowerValue: $lo, upperValue: $hi, bounds: 0...100) { value in
                Text("\(Int(value)) min")
                    .font(.caption2)
                    .foregroundStyle(.secondary)
                    .padding(.bottom)
            }

            // No label
            RangeSlider(lowerValue: $lo, upperValue: $hi,
                        bounds: 0...100, step: 5, minimumSpan: 10)
                .tint(.orange)

            RangeSlider(lowerValue: $loF, upperValue: $hiF, bounds: 0...1)
                .tint(.green)

            VStack(alignment: .leading, spacing: 4) {
                Text("lo \(lo, format: .number.precision(.fractionLength(1)))  –  hi \(hi, format: .number.precision(.fractionLength(1)))")
                    .monospacedDigit()
                    .font(.caption)
                    .foregroundStyle(.secondary)
                Text("loF \(loF, format: .number.precision(.fractionLength(2)))  –  hiF \(hiF, format: .number.precision(.fractionLength(2)))")
                    .monospacedDigit()
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
        .padding(32)
    }
}
