# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
    build_app(scheme: "PennMobile")
    api_key = app_store_connect_api_key(
        key_id: "YB62BFTN48",
        issuer_id: "69a6de6f-64eb-47e3-e053-5b8c7c11a4d1",
        key_filepath: "./AuthKey_YB62BFTN48.p8",
        duration: 1200, # optional (maximum 1200)
        in_house: false # optional but may be required if using match/sigh
    )
    pilot(app_identifier: "org.pennlabs.PennMobile", api_key: api_key)
  end

  lane :ci_build do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
    increment_build_number({
      build_number: latest_testflight_build_number(api_key_path: "api_key.json", app_identifier: "org.pennlabs.PennMobile") + 1
    })
    
    build_app(
        scheme: "PennMobile",
        output_name: "PennMobile.ipa",
        export_options: {
            provisioningProfiles: {
                "org.pennlabs.PennMobile" => "Penn Mobile - Distribution",
                "org.pennlabs.PennMobile.Widget" => "Penn Mobile Widget - Distribution"
            }
        }
    )
  end

  lane :ci_pilot do
    pilot(
      app_identifier: "org.pennlabs.PennMobile",
      api_key_path: "api_key.json",
      ipa: "PennMobile.ipa",
      distribute_external: true,
      groups: "Penn Labs",
      changelog: "Test experimental features of Penn Mobile",
      beta_app_description: "Test experimental features of Penn Mobile",
      beta_app_feedback_email: "contact@pennlabs.org"
    )
  end
  
  lane :deployBeta do
    api_key = app_store_connect_api_key(
        key_id: "YB62BFTN48",
        issuer_id: "69a6de6f-64eb-47e3-e053-5b8c7c11a4d1",
        key_filepath: "./AuthKey_YB62BFTN48.p8",
        duration: 1200, # optional (maximum 1200)
        in_house: false # optional but may be required if using match/sigh
    )
    
    pilot(app_identifier: "org.pennlabs.PennMobile", api_key: api_key)
  end

end
