# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate app screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "PennMobile.xcworkspace", scheme: "AutomatedScreenshotUITests")
  end

  desc "Frame all screenshots"
  lane :frame do
    frameit(white: true, path: './fastlane/screenshots')
  end

  desc "Capture and frame new screenshots"
  lane :capture_and_frame do
    capture_screenshots(workspace: "PennMobile.xcworkspace", scheme: "AutomatedScreenshotUITests")
    frameit(white: true, path: './fastlane/screenshots')
  end

end
