# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate app screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "PennMobile.xcworkspace", scheme: "AutomatedScreenshotUITests")
  end

  desc "Frame all screenshots"
  lane :frame do
    frameit(white: true, path: './fastlane/screenshots')
  end

  desc "Capture and frame new screenshots"
  lane :capture_and_frame do
    capture_screenshots(workspace: "PennMobile.xcworkspace", scheme: "AutomatedScreenshotUITests")
    frameit(white: true, path: './fastlane/screenshots')
  end

  lane :beta do
    build_app(scheme: "PennMobile")
    api_key = app_store_connect_api_key(
        key_id: "YB62BFTN48",
        issuer_id: "69a6de6f-64eb-47e3-e053-5b8c7c11a4d1",
        key_filepath: "./AuthKey_YB62BFTN48.p8",
        duration: 1200, # optional (maximum 1200)
        in_house: false # optional but may be required if using match/sigh
    )
    pilot(app_identifier: "org.pennlabs.PennMobile", api_key: api_key)
  end

  lane :ci_beta do
    increment_build_number({
      build_number: latest_testflight_build_number(api_key_path: "api_key.json", app_identifier: "org.pennlabs.PennMobile") + 1
    })
    build_app(scheme: "PennMobile")
    pilot(app_identifier: "org.pennlabs.PennMobile", api_key_path: "api_key.json", distribute_external: true, groups: "Penn Labs", reject_build_waiting_for_review: true, changelog: "test CI")
  end
  
  lane :deployBeta do
    api_key = app_store_connect_api_key(
        key_id: "YB62BFTN48",
        issuer_id: "69a6de6f-64eb-47e3-e053-5b8c7c11a4d1",
        key_filepath: "./AuthKey_YB62BFTN48.p8",
        duration: 1200, # optional (maximum 1200)
        in_house: false # optional but may be required if using match/sigh
    )
    
    pilot(app_identifier: "org.pennlabs.PennMobile", api_key: api_key)
  end

end
